name: "Test application"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5

      - name: Set up the Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"

      - name: Build with Maven and run tests
        run: mvn test --batch-mode
